[book]
title = "libr0: Building Rust's Standard Library from Scratch"
authors = ["Arinal"]
language = "en"
src = "."

[build]
build-dir = "book"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/arinal/libr0"
additional-js = ["mermaid.min.js", "mermaid-init.js", "theme/landing.js"]
# additional-css = ["theme/custom.css", "theme/landing.css"]

[output.html.search]
enable = true
limit-results = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[preprocessor.svgbob]
command = "mdbook-svgbob"

[preprocessor.mermaid]
command = "mdbook-mermaid"
